name: mobcommonlib
description: Flutter plugin for common lib used by MobTech SDK.
version: 1.1.4
homepage: https://www.mob.com/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mob.flutter.mobcommonlib
        pluginClass: MobcommonlibPlugin
      ios:
        pluginClass: MobcommonlibPlugin
